"""Initial migration

Revision ID: b1e9cd909996
Revises: e41a3cdd243b
Create Date: 2025-03-29 18:06:40.620589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1e9cd909996'
down_revision: Union[str, None] = 'e41a3cdd243b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('emissions', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'emissions')
    # ### end Alembic commands ###
